import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readEducationContent } from "./content-reader.mjs";

const OUTPUT_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../apps/web/src/features/education/education-content.generated.ts"
);

export async function generateContentModule(outputPath = OUTPUT_PATH) {
  const content = await readEducationContent();
  const articles = content.articles.map(({ sourcePath: _sourcePath, bodyMarkdown: _bodyMarkdown, ...article }) => article);
  const source = [
    "// This file is generated by tools/education/generate-content.mjs.",
    "// Do not edit it directly; update docs/education/articles instead.",
    "",
    `export const educationCategories = ${JSON.stringify(content.categories, null, 2)} as const;`,
    "",
    `export const educationArticles = ${JSON.stringify(articles, null, 2)} as const;`,
    ""
  ].join("\n");

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source, "utf8");
  return { outputPath, articleCount: articles.length };
}

async function main() {
  const result = await generateContentModule();
  process.stdout.write(`Education content generated: ${result.articleCount} articles\n`);
}

if (
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main().catch((error) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`
    );
    process.exitCode = 1;
  });
}
